global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "baseline_service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["baseline-awareness-service:80"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: "instance"

  - job_name: "baseline_service_multiproc"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["baseline-awareness-service:80"]
    honor_labels: true

  - job_name: "blackbox_http_docs"
    metrics_path: "/probe"
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "baseline-awareness-service:80/docs"
          - "baseline-awareness-service:80/openapi.json"
          - "planner-service:8000/docs"
          - "planner-service:8000/openapi.json"
          - "fountainai-bootstrap-service:8000/docs"
          - "fountainai-bootstrap-service:8000/openapi.json"
          - "llm-gateway-service:8000/docs"
          - "llm-gateway-service:8000/openapi.json"
          - "registry-service:5000/v2/"
    relabel_configs:
      - source_labels: [__address__]
        target_label: "__param_target"
      - target_label: "__address__"
        replacement: "blackbox-exporter:9115"
      - source_labels: [__param_target]
        target_label: "instance"
